name: segcolr-env
channels:
  - conda-forge
  - huggingface
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy<2.0
  - opencv
  - pillow
  - matplotlib
  - plotly
  - requests
  - pytorch
  - torchvision
  - transformers
  - pip:
    - git+https://github.com/huggingface/transformers

